### ISSUE TITLE
[1.7.10] Log extreme spam caused by tile entity reset fix

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#170]
**To Reproduce**
1. Make a world
2. Show the log spam

log spam example : 

```
[14:27:08] [Server thread/ERROR] [TEResetFix]: Cannot invoke dormantChunkCache! The mod will not work properly and you should report this as a bug.
java.lang.invoke.WrongMethodTypeException: expected ()Map but found (ForgeChunkManager)Map
	at java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:298) ~[?:1.8.0_302]
	at java.lang.invoke.Invokers.checkExactType(Invokers.java:309) ~[?:1.8.0_302]
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesTE.fetchDormantChunk(MysteriumPatchesFixesTE.java:42) [MysteriumPatchesFixesTE.class:?]
	at net.minecraftforge.common.ForgeChunkManager.fetchDormantChunk(ForgeChunkManager.java:911) [ForgeChunkManager.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:156) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) [ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) [aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715) [mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
java.lang.invoke.WrongMethodTypeException: expected ()Map but found (ForgeChunkManager)Map
	at java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:298) ~[?:1.8.0_302]
	at java.lang.invoke.Invokers.checkExactType(Invokers.java:309) ~[?:1.8.0_302]
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesTE.fetchDormantChunk(MysteriumPatchesFixesTE.java:42) [MysteriumPatchesFixesTE.class:?]
	at net.minecraftforge.common.ForgeChunkManager.fetchDormantChunk(ForgeChunkManager.java:911) [ForgeChunkManager.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:156) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) [ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) [aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715) [mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[14:27:08] [Server thread/ERROR] [TEResetFix]: Something went wrong. The mod will not work properly and you should report this as a bug.
java.lang.NullPointerException
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesTE.fetchDormantChunk(MysteriumPatchesFixesTE.java:46) [MysteriumPatchesFixesTE.class:?]
	at net.minecraftforge.common.ForgeChunkManager.fetchDormantChunk(ForgeChunkManager.java:911) [ForgeChunkManager.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:156) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) [ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) [aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715) [mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
	```

**Comment by quentin452** [comment]
caused by own disabled for now

**Comment by quentin452** [comment]
fixed by the developper
