### ISSUE TITLE
[1.12.2] When host a world with essentials i get this errors

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#198]
result : other player cannot connect to my lan server 

io.netty.handler.codec.EncoderException: String too big (was 35371 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:50)
	at net.minecraft.network.status.server.SPacketServerInfo.func_148840_b(SourceFile:41)
	at net.minecraft.server.MinecraftServer.handler$bmk000$publishUpdatedStatus(MinecraftServer.java:5249)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.handler$zbi000$newWhileLoop(MinecraftServer.java:2301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493)
	at java.lang.Thread.run(Thread.java:826)
io.netty.handler.codec.EncoderException: String too big (was 35371 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:50)
	at net.minecraft.network.status.server.SPacketServerInfo.func_148840_b(SourceFile:41)
	at net.minecraft.server.MinecraftServer.handler$bmk000$publishUpdatedStatus(MinecraftServer.java:5249)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.handler$zbi000$newWhileLoop(MinecraftServer.java:2301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493)
	at java.lang.Thread.run(Thread.java:826)
io.netty.handler.codec.EncoderException: String too big (was 35371 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:50)
	at net.minecraft.network.status.server.SPacketServerInfo.func_148840_b(SourceFile:41)
	at net.minecraft.server.MinecraftServer.handler$bmk000$publishUpdatedStatus(MinecraftServer.java:5249)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.handler$zbi000$newWhileLoop(MinecraftServer.java:2301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493)
	at java.lang.Thread.run(Thread.java:826)
io.netty.handler.codec.EncoderException: String too big (was 35371 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:50)
	at net.minecraft.network.status.server.SPacketServerInfo.func_148840_b(SourceFile:41)
	at net.minecraft.server.MinecraftServer.handler$bmk000$publishUpdatedStatus(MinecraftServer.java:5249)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.handler$zbi000$newWhileLoop(MinecraftServer.java:2301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493)
	at java.lang.Thread.run(Thread.java:826)
io.netty.handler.codec.EncoderException: String too big (was 35371 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:50)
	at net.minecraft.network.status.server.SPacketServerInfo.func_148840_b(SourceFile:41)
	at net.minecraft.server.MinecraftServer.handler$bmk000$publishUpdatedStatus(MinecraftServer.java:5249)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.handler$zbi000$newWhileLoop(MinecraftServer.java:2301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493)
	at java.lang.Thread.run(Thread.java:826)
io.netty.handler.codec.EncoderException: String too big (was 35371 bytes encoded, max 32767)
	at net.minecraft.network.PacketBuffer.func_180714_a(PacketBuffer.java:50)
	at net.minecraft.network.status.server.SPacketServerInfo.func_148840_b(SourceFile:41)
	at net.minecraft.server.MinecraftServer.handler$bmk000$publishUpdatedStatus(MinecraftServer.java:5249)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:683)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.handler$zbi000$newWhileLoop(MinecraftServer.java:2301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:493)

**Comment by quentin452** [comment]
fixed by changing the packet size limit in randompatches

**Comment by quentin452** [comment]
fixed by removing flux network and adding an alternative : tesseract in V6.0modifiedbeta3

**Comment by quentin452** [comment]
Other mod make this

**Comment by quentin452** [comment]
server not supported anymore since V6.0modifiedbeta4
