### ISSUE TITLE
[1.12.2] When exiting a world i have voxelmap error about calculation

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#199]

**Comment by quentin452** [comment]
Exception in thread "Voxelmap WorldMap Calculation Thread 6" java.lang.NullPointerException
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.createKeyFromCurrentBlocks(CompressibleMapData.java:399)
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.getStateToInt(CompressibleMapData.java:378)
	at com.mamiyaotaru.voxelmap.persistent.CachedRegion$1.run(CachedRegion.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:826)
Exception in thread "Voxelmap WorldMap Calculation Thread 3" java.lang.NullPointerException
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.createKeyFromCurrentBlocks(CompressibleMapData.java:399)
	at com.mamiyaotaru.voxelmap.persistent.CompressibleMapData.getStateToInt(CompressibleMapData.java:378)
	at com.mamiyaotaru.voxelmap.persistent.CachedRegion$1.run(CachedRegion.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:826)

**Comment by quentin452** [comment]
voxelmap deleted in V6.0modifiedbeta4
