### ISSUE TITLE
[1.7.10] Crash when make a world spam log

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#281]
```
: Exception caught during firing event net.minecraftforge.event.terraingen.PopulateChunkEvent$Post@43a677f8:
net.minecraft.util.ReportedException: Getting block
	at net.minecraft.world.World.func_147439_a(World.java:354) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at magicbees.world.feature.FeatureOreVein.generateVein(FeatureOreVein.java:46) ~[FeatureOreVein.class:?]
	at magicbees.bees.HiveDescription$2.postGen(HiveDescription.java:81) ~[HiveDescription$2.class:?]
	at forestry.apiculture.worldgen.Hive.postGen(Hive.java:56) ~[Hive.class:?]
	at forestry.apiculture.worldgen.HiveDecorator.setHive(HiveDecorator.java:148) ~[HiveDecorator.class:?]
	at forestry.apiculture.worldgen.HiveDecorator.tryGenHive(HiveDecorator.java:129) ~[HiveDecorator.class:?]
	at forestry.apiculture.worldgen.HiveDecorator.genHive(HiveDecorator.java:79) ~[HiveDecorator.class:?]
	at forestry.apiculture.worldgen.HiveDecorator.decorateHives(HiveDecorator.java:54) ~[HiveDecorator.class:?]
	at forestry.apiculture.worldgen.HiveDecorator.decorateHives(HiveDecorator.java:41) ~[HiveDecorator.class:?]
	at forestry.plugins.PluginApiculture.populateChunk(PluginApiculture.java:1143) ~[PluginApiculture.class:?]
	at forestry.plugins.PluginManager.populateChunk(PluginManager.java:347) ~[PluginManager.class:?]
	at forestry.core.worldgen.WorldGenerator.populateChunk(WorldGenerator.java:44) ~[WorldGenerator.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_3105_WorldGenerator_populateChunk_Post.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at DelirusCrux.Netherlicious.Dimension.NetherChunkProvider.func_73153_a(NetherChunkProvider.java:1052) [NetherChunkProvider.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenObsidianBeach.func_76484_a(WorldGenObsidianBeach.java:38) [WorldGenObsidianBeach.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:75) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:23) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenBigNetherMushroom.func_76484_a(WorldGenBigNetherMushroom.java:61) [WorldGenBigNetherMushroom.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:60) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenSpikes.func_76484_a(WorldGenSpikes.java:24) [WorldGenSpikes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:78) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:82) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:82) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.chocolatemc.worldGen.FireTreeGen.func_76484_a(FireTreeGen.java:85) [FireTreeGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generateNether(WorldGen.java:55) [WorldGen.class:?]
	at com.chocolatemc.worldGen.WorldGen.generate(WorldGen.java:33) [WorldGen.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:23) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:82) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:23) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
	at com.superdextor.dextersnether.worldgen.WorldGenAcidLakes.func_76484_a(WorldGenAcidLakes.java:23) [WorldGenAcidLakes.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generateNether(NetherGeneration.java:66) [NetherGeneration.class:?]
	at com.superdextor.dextersnether.NetherGeneration.generate(NetherGeneration.java:43) [NetherGeneration.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]

**Comment by quentin452** [comment]
fixed by removing EvilSky-1.7.10-1.0.1
