### ISSUE TITLE
[1.7.10] Crash on startup "JVMCFRE106 méthode en double; classe=net/minecraft/block/BlockGlass, décalage=942 	at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_362]"

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#285]
```
[09:57:07] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net.minecraft.block.BlockGlass
	at net.minecraft.block.Block.func_149671_p(Block.java:224) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockGlass
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_362]
	at net.minecraft.block.Block.func_149671_p(Block.java:224) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassFormatError: JVMCFRE106 méthode en double; classe=net/minecraft/block/BlockGlass, décalage=942
	at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_362]
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397) ~[?:1.8.0_362]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358) ~[?:1.8.0_362]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ~[?:1.8.0_362]
	at net.minecraft.block.Block.func_149671_p(Block.java:224) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
	```

**Comment by quentin452** [comment]
fixed by removing RedGearCore-1.7.10-2.2.2
