### ISSUE TITLE
[1.7.10] Crash on startup "java.lang.NoClassDefFoundError: net.minecraft.client.renderer.texture.TextureMap"

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#286]
```
java.lang.NoClassDefFoundError: net.minecraft.client.renderer.texture.TextureMap
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5993)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:902)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:885)
	... 17 more

**Comment by quentin452** [comment]
fixed by disabling speedupAnimations in hodgepodge.cfg
