### ISSUE TITLE
[1.7.10] Crash when destroying blocks(gamemode 0)

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#334]
```
[22:37:07] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@3be55f11:
java.lang.NullPointerException
	at club.someoneice.spawner.SpawnerMain.onPlayerUse(SpawnerMain.java:29) ~[SpawnerMain.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2567_SpawnerMain_onPlayerUse_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:140) [mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489) [nh.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53) [ji.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) [ji.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesF.tick(MysteriumPatchesFixesF.java:51) [MysteriumPatchesFixesF.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by quentin452** [comment]
fixed in V0.29hotfix 2 by removing  better_spawner-1.0
