### ISSUE TITLE
[1.7.10] Twillight forest crash when tp id=7

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#338]
java.lang.RuntimeException: Chunk build failed
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:593)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:249)
	at net.minecraft.client.renderer.RenderGlobal.func_72729_a(RenderGlobal.java:8266)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:3306)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:3118)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:9006)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException
	at twilightforest.block.BlockTFLeaves.func_149673_e(BlockTFLeaves.java:519)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4445)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at lotr.common.coremod.LOTRReplacedMethods$BlockRendering.renderStandardBlock(LOTRReplacedMethods.java:155)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:105)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:177)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
	at java.lang.Thread.run(Thread.java:750)

**Comment by quentin452** [comment]
seem its an issue caused by endlessids

**Comment by quentin452** [comment]
due to adding LOTR mod in V0.89.6 , i need to disabling the Twilight forest dim(because there is no space in the vanilla range of biomeid), need to fix crash when an biomeid from Twilightforest is higher than 255

**Comment by GamebP** [comment]
edit Twillight forest code. Allow max be 1234.

**Comment by quentin452** [comment]
not

**Comment by quentin452** [comment]
Fixed in Biggess Pack Cat Edition V0.98.8 by updating twilight forest and angelica
