### ISSUE TITLE
[1.7.10] Spam log when get killed

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#370]
```
[15:17:57] [Server thread/ERROR] [AE2 Tech Add-On]: [Ljava.lang.StackTraceElement;@eb4233ef
[15:17:57] [Server thread/INFO] [STDOUT]: [com.darva.parachronology.handlers.PlayerExtender:loadNBTData:23]: LoadNBT
java.io.FileNotFoundException: https://raw.githubusercontent.com/Raizunne/Redstonic/master/src/versions/latest.txt
[15:17:57] [Client thread/INFO] [FML]: [REDSTONIC]: Using latest version.
[15:17:57] [Client thread/INFO]: [CHAT] Magic Yarn found on server.
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1898)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
	at java.security.AccessController.doPrivileged(AccessController.java:953)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:993)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.raizunne.redstonic.Proxy.ClientProxy.checkVersion(ClientProxy.java:55)
	at com.raizunne.redstonic.Handler.RedstonicEventHandler.LoginEvent(RedstonicEventHandler.java:75)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1339_RedstonicEventHandler_LoginEvent_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71354_a(Minecraft.java:2286)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:879)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6506)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by quentin452** [comment]
fixed by removing Redstonic in V0.58
