### ISSUE TITLE
[1.7.10] Crash server when prestorian creeper explodes(sometimes)

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#385]
```

java.lang.NullPointerException: Ticking entity
	at com.debbie.nsn.handler.nsnBlockDropHandler.onDrops(nsnBlockDropHandler.java:33)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1966_nsnBlockDropHandler_onDrops_HarvestDropsEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
	at net.minecraft.block.Block.func_149690_a(Block.java:656)
	at net.minecraft.block.BlockOre.func_149690_a(BlockOre.java:54)
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:212)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:902)
	at net.minecraft.world.World.func_72876_a(World.java:2403)
	at toast.specialMobs.entity.creeper.Entity_SpecialCreeper.explodeByType(Entity_SpecialCreeper.java:190)
	at toast.specialMobs.entity.creeper.Entity_SpecialCreeper.func_70071_h_(Entity_SpecialCreeper.java:171)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1646)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by quentin452** [comment]
fixed in V0.77.1 by disabling speicalmobs creeper in special mobs config
