### ISSUE TITLE
[1.12.2]: Enabling debbugging things in renderlib can make crash caused by codechickenlib when world joining

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#418]
### Modpack

V6.0modifiedstable6 Mystics Monstrosity

### Game log

[crash-2023-08-03_01.05.36-client.txt](https://github.com/quentin452/privates-minecraft-modpack/files/12245402/crash-2023-08-03_01.05.36-client.txt)

### Description

So i enabled theses things in renderlib
and i got crash when joining a world caused by codechickencore (the issue only appear with debugs enabled)
![image](https://github.com/quentin452/privates-minecraft-modpack/assets/42176772/39bee967-a853-43ef-a6d6-6b18e8050c15)

**Comment by quentin452** [comment]
i think it should be fixed by removing WR-CBE-1.12.2-2.3.2.33-universal

i reviewed the logs file that maked the crash and i see this during worldgeneration so i think its not a coincidence, so i think the mod that make the crash is wireless redstone CBE
```
[FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@7a2b14cb:
java.lang.NullPointerException: null
    at codechicken.wirelessredstone.handler.WREventHandler.worldTick(WREventHandler.java:170) ~[WREventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_5641_WREventHandler_worldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
```
