### ISSUE TITLE
[1.7.10]: Doggy talent Texture index bug on dog(fixed) + bed(not fixed)

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#440]
### Modpack

Biggess Pack Cat Edtition V0.85.64

### Game log

i got this error
```
java.io.FileNotFoundException: doggytalents:textures/mob/dog/doggytex127.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:51) [bno.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110777_b(SourceFile:47) [bno.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_77036_a(RendererLivingEntity.java:286) [boh.class:?]
	at doggytalents.client.renderer.entity.RenderDog.func_77036_a(RenderDog.java:69) [RenderDog.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:149) [boh.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23) [bok.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:11) [bok.class:?]
	at doggytalents.client.renderer.entity.RenderDog.func_76986_a(RenderDog.java:56) [RenderDog.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271) [bnn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244) [bnn.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471) [bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224) [blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6506) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```

### Description

screenshot : 

![Capture d’écran_2023-08-20_14-25-34](https://github.com/quentin452/privates-minecraft-modpack/assets/42176772/1ae7b0a0-618c-4ead-98a0-b26c4a3a6cad)

note : 

the texture index can be changed by using a stick on a dog from doggy talent and chaing texture index

**Comment by quentin452** [comment]
Also the dog bed texture is missing

**Comment by quentin452** [comment]
Doggy talent by default have these bugs so this issue will be closed has not planned
