### ISSUE TITLE
[1.7.10]: Kicked out of server

### ISSUE THREAD

**Issue by Bleb1k** [quentin452/1.7.10-Forge-renewed-v1#523]
### Modpack

Biggess pack cat edition

### Game log

[18:52:08] [Client thread/INFO] [STDOUT]: [xaero.common.minimap.write.MinimapWriter:loadBlockColourFromTexture:1456]: Block file not found: Metallurgy:fantasy.ore
[18:52:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2225) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:2573) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2316) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.lang.NullPointerException
	at fr.elias.morecreeps.common.entity.CREEPSEntityHorseHead.func_70601_bi(CREEPSEntityHorseHead.java:266) ~[CREEPSEntityHorseHead.class:?]
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:740) ~[aho.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2221) ~[MinecraftServer.class:?]
	... 4 more

### Description

Suddenly kicked out of server

**Comment by quentin452** [comment]
Fixed in V0.86.2.1
