### ISSUE TITLE
[1.7.10]: Lotr Crash on startup at 3/7

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#524]
### Modpack

Biggess Pack Cat Edition V0.87

### Game log

[00:08:40] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[00:08:40] [Client thread/ERROR] [FML]: Caught exception from lotr
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    lotr/common/block/LOTRBlockReplacement.replaceVanillaBlock(Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;Ljava/lang/Class;)V @271: aload
  Reason:
    Type top (current frame, locals[10]) is not assignable to reference type
  Current Frame:
    bci: @271
    flags: { }
    locals: { 'net/minecraft/block/Block', 'net/minecraft/block/Block', 'java/lang/Class', integer, 'java/lang/String', 'java/lang/String', 'java/lang/String', 'net/minecraft/item/Item', 'java/lang/reflect/Constructor', 'net/minecraft/item/ItemBlock' }
    stack: { }
  Bytecode:
    0x0000000: b200 f82a b600 fe3e 2ab8 0102 3a04 b200
    0x0000010: f82a b601 063a 0519 043a 062a b801 0a3a
    0x0000020: 0719 07c6 000a 1907 b801 0e3a 062a b801
    0x0000030: 152a b801 152b 1904 b601 1957 2a2b b801
    0x0000040: 1d2b b401 212a b401 21b9 0126 0100 b801
    0x0000050: 2ab2 00f8 b801 2e2b 1db6 0134 b200 f8b8
    0x0000060: 0138 1905 2bb9 013c 0300 572b 1905 b801
    0x0000070: 40b2 0142 9a00 19bb 0017 59b2 0147 b700
    0x0000080: 5eb2 014c 03b8 0152 5704 b301 4203 3608
    0x0000090: 1508 100f a300 1b2b 2a15 08b6 0156 2a15
    0x00000a0: 08b6 015a 1508 b601 5e84 0801 a7ff e42c
    0x00000b0: c600 722c 04bd 0110 5903 12f4 53b6 0162
    0x00000c0: 3a08 1908 04bd 0004 5903 2b53 b601 68c0
    0x00000d0: 016a 3a09 1909 1906 b601 6e57 1907 c600
    0x00000e0: 3819 09b4 016f 1907 b401 70b9 0126 0100
    0x00000f0: b801 2ab2 0173 b801 2e19 091d b601 34b2
    0x0000100: 0173 b801 3819 0519 09b9 013c 0300 5719
    0x0000110: 0a19 05b8 0177 1d2b 1909 b801 7919 09b8
    0x0000120: 017b a700 203a 0913 017d 04bd 0004 5903
    0x0000130: 2ab6 0180 53b8 0185 bb01 8759 1909 b701
    0x0000140: 8abf b1                                
  Exception Handler Table:
    bci [0, 290] => handler: 293
  Stackmap Table:
    full_frame(@45,{Object[#244],Object[#244],Object[#272],Integer,Object[#144],Object[#144],Object[#144],Object[#111]},{})
    same_frame_extended(@141)
    append_frame(@144,Integer)
    chop_frame(@175,1)
    append_frame(@278,Object[#356],Object[#362])
    full_frame(@290,{Object[#244],Object[#244],Object[#272]},{})
    same_locals_1_stack_item_frame(@293,Object[#242])
    same_frame(@322)
	at lotr.common.LOTRMod.preload(LOTRMod.java:2134) ~[LOTRMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:9332) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

### Description

crash on startup at 3/7 with LOTR

**Comment by quentin452** [comment]
Fixed by removing LOTR-UCP-1.3.0.jar
