### ISSUE TITLE
[1.7.10]: Freeze server when generating world with seed : 1112337741283820816(Caused by Tropics dimension)

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#541]
### Modpack

Biggess Pack Cat Edition V0.89.9 DEV

### Game log

no logs

### Description

no description

**Comment by quentin452** [comment]
probably need to update Tropicraft

here is the error i get with CasCadingworldgenStacktrace enabled

```
java.lang.Exception: Cascading world generation
	at net.minecraft.world.chunk.Chunk.logCascadingWorldGeneration(Chunk.java:6161) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zlp000$archaicfix$savePopulatingChunk(Chunk.java:6167) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.tropicraft.world.worldgen.WorldGenForestAltarRuin.generate(WorldGenForestAltarRuin.java:42) ~[WorldGenForestAltarRuin.class:?]
	at net.tropicraft.world.biomes.BiomeGenRainforest.func_76728_a(BiomeGenRainforest.java:36) ~[BiomeGenRainforest.class:?]
	at net.tropicraft.world.chunk.ChunkProviderTropicraft.func_73153_a(ChunkProviderTropicraft.java:340) ~[ChunkProviderTropicraft.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.tropicraft.world.worldgen.WorldGenTallFlower.generate(WorldGenTallFlower.java:27) ~[WorldGenTallFlower.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropicraft.func_76728_a(BiomeGenTropicraft.java:82) ~[BiomeGenTropicraft.class:?]
	at net.tropicraft.world.biomes.BiomeGenRainforest.func_76728_a(BiomeGenRainforest.java:68) ~[BiomeGenRainforest.class:?]
	at net.tropicraft.world.chunk.ChunkProviderTropicraft.func_73153_a(ChunkProviderTropicraft.java:340) ~[ChunkProviderTropicraft.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.tropicraft.world.worldgen.WorldGenTallFlower.generate(WorldGenTallFlower.java:27) ~[WorldGenTallFlower.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropicraft.func_76728_a(BiomeGenTropicraft.java:82) ~[BiomeGenTropicraft.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropics.func_76728_a(BiomeGenTropics.java:37) ~[BiomeGenTropics.class:?]
	at net.tropicraft.world.chunk.ChunkProviderTropicraft.func_73153_a(ChunkProviderTropicraft.java:340) ~[ChunkProviderTropicraft.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.tropicraft.world.worldgen.WorldGenTallFlower.generate(WorldGenTallFlower.java:27) ~[WorldGenTallFlower.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropicraft.func_76728_a(BiomeGenTropicraft.java:82) ~[BiomeGenTropicraft.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropics.func_76728_a(BiomeGenTropics.java:37) ~[BiomeGenTropics.class:?]
	at net.tropicraft.world.chunk.ChunkProviderTropicraft.func_73153_a(ChunkProviderTropicraft.java:340) ~[ChunkProviderTropicraft.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.tropicraft.world.worldgen.WorldGenTallFlower.generate(WorldGenTallFlower.java:27) ~[WorldGenTallFlower.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropicraft.func_76728_a(BiomeGenTropicraft.java:82) ~[BiomeGenTropicraft.class:?]
	at net.tropicraft.world.biomes.BiomeGenTropics.func_76728_a(BiomeGenTropics.java:37) ~[BiomeGenTropics.class:?]
	at net.tropicraft.world.chunk.ChunkProviderTropicraft.func_73153_a(ChunkProviderTropicraft.java:340) ~[ChunkProviderTropicraft.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:1577) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65) ~[bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2286) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
