### ISSUE TITLE
[1.7.10]: Crash Exception ticking world caused by Fossil And Archeology

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#550]
### Modpack

V0.90.8 DEV

### Game log

```
[11:56:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2230) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:2572) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2329) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.error(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
	at net.minecraft.world.World.func_147439_a(World.java:56631) ~[ahb.class:?]
	at fossilsarcheology.server.block.BlockPermafrost.func_149674_a(BlockPermafrost.java:71) ~[BlockPermafrost.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:1324) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2226) ~[MinecraftServer.class:?]
	... 4 more
```
### Description

no description

**Comment by quentin452** [comment]
Fixed in V0.90.8 by updating Optimizationsandtweaks
