### ISSUE TITLE
[1.7.10]: DungeonMob made 9000 reports of cascading worldgens when teleported to a specifiq location

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#553]
### Modpack

V0.90.8HOTFIX DEV

### Game log

[fml-client-1.log.zip](https://github.com/quentin452/privates-minecraft-modpack/files/13648483/fml-client-1.log.zip)

when searching : com.gw.dm.DungeonMobsWorldGenEvent.generateTraps you will see about 9000 lines of it

### Description

![Capture d’écran_2023-12-12_13-59-15](https://github.com/quentin452/privates-minecraft-modpack/assets/42176772/c6390aa8-b168-400a-a045-dffc980c392e)

when teleporting to location -497 100 432 with seed -6346555249212216979 he make aboat 9000 reports of cascading worldgens
```
java.lang.Exception: Cascading world generation
	at net.minecraft.world.chunk.Chunk.logCascadingWorldGeneration(Chunk.java:5661) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zlp000$archaicfix$savePopulatingChunk(Chunk.java:5667) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at com.gw.dm.DungeonMobsWorldGenEvent.generateTraps(DungeonMobsWorldGenEvent.java:160) ~[DungeonMobsWorldGenEvent.class:?]
	at com.gw.dm.DungeonMobsWorldGenEvent.onPopulateChunk(DungeonMobsWorldGenEvent.java:42) ~[DungeonMobsWorldGenEvent.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2779_DungeonMobsWorldGenEvent_onPopulateChunk_Populate.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:36) ~[TerrainGen.class:?]
	at fr.iamacat.optimizationsandtweaks.worldgen.ChunkProviderGenerateTwo.func_73153_a(ChunkProviderGenerateTwo.java:475) ~[ChunkProviderGenerateTwo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at zeldaswordskills.world.gen.structure.MapGenSongPillar.canGenerateAt(MapGenSongPillar.java:233) ~[MapGenSongPillar.class:?]
	at zeldaswordskills.world.gen.structure.MapGenSongPillar.generate2(MapGenSongPillar.java:98) ~[MapGenSongPillar.class:?]
	at zeldaswordskills.world.gen.structure.MapGenSongPillar.generate(MapGenSongPillar.java:90) ~[MapGenSongPillar.class:?]
	at zeldaswordskills.world.gen.ZSSWorldGenEvent.postPopulate(ZSSWorldGenEvent.java:71) ~[ZSSWorldGenEvent.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1952_ZSSWorldGenEvent_postPopulate_Post.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at fr.iamacat.optimizationsandtweaks.worldgen.ChunkProviderGenerateTwo.func_73153_a(ChunkProviderGenerateTwo.java:491) ~[ChunkProviderGenerateTwo.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.SpawnerAnimals.func_151350_a(SpawnerAnimals.java:32) ~[aho.class:?]
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:651) ~[aho.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2226) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:2572) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2329) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]

```
so L'ill probably make a fork of Dungeon mob to fix the problem

**Comment by quentin452** [comment]
Don't have clue so i disabled Traps generation BY updating the the mod in V0.90.8
