### ISSUE TITLE
[1.7.10]: Add Immersive Engineering mod

### ISSUE THREAD

**Issue by xronin01** [quentin452/1.7.10-Forge-renewed-v1#655]
### Modpack

Biggess Pack Cat Edition

### Description

https://www.curseforge.com/minecraft/mc-mods/immersive-engineering

**Comment by quentin452** [comment]
need to fix an infinite loop that stop world generating and the error
![image](https://github.com/quentin452/privates-minecraft-modpack/assets/42176772/bdb8491a-64f5-4e2f-9d27-5f68943d1aac)
```
Exception in thread "Immersive Engineering Registry Iteratoration Thread" [05:57:14] [Immersive Engineering Registry Iteratoration Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[05:57:14] [Immersive Engineering Registry Iteratoration Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
[05:57:14] [Immersive Engineering Registry Iteratoration Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.ArrayList.get(ArrayList.java:435)
[05:57:14] [Immersive Engineering Registry Iteratoration Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
[05:57:14] [Immersive Engineering Registry Iteratoration Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler.getRecycleCalculation(ArcRecyclingThreadHandler.java:192)
[05:57:14] [Immersive Engineering Registry Iteratoration Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at blusunrize.immersiveengineering.common.crafting.ArcRecyclingThreadHandler$RegistryIterationThread.run(ArcRecyclingThreadHandler.java:147)
Le processus a été interrompu par l'utilisateur.

**Comment by xronin01** [comment]
try this fork 
https://github.com/vladislemon/ImmersiveEngineering

**Comment by quentin452** [comment]
when the bug get fixed , add the addon : Middle-Earth Industry

**Comment by quentin452** [comment]
Middle-Earth Industry crash on startup so not added

**Comment by quentin452** [comment]
Immersive Engineering Added in V0.95.6 (Fixed these bugs by making a fork)
