### ISSUE TITLE
[1.7.10]: Add Atum mod

### ISSUE THREAD

**Issue by xronin01** [quentin452/1.7.10-Forge-renewed-v1#662]
### Modpack

Biggess Pack Cat Edition

### Description

https://www.curseforge.com/minecraft/mc-mods/atum

**Comment by quentin452** [comment]
probably need to fix this crash if it happen again
```
java.lang.NullPointerException: Exception getting block type in world
	at com.teammetallurgy.atum.items.AtumWeightedLootSet.getRandomLoot(AtumWeightedLootSet.java:54)
	at com.teammetallurgy.atum.items.AtumLoot.fillChest(AtumLoot.java:44)
	at com.teammetallurgy.atum.world.decorators.WorldGenPyramid.func_76484_a(WorldGenPyramid.java:108)
	at com.teammetallurgy.atum.world.biome.BiomeGenAtumDesert.func_76728_a(BiomeGenAtumDesert.java:92)
	at com.teammetallurgy.atum.world.AtumChunkProvider.func_73153_a(AtumChunkProvider.java:446)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by quentin452** [comment]
Added in V0.94
