### ISSUE TITLE
[1.7.10]: TinkerConstruct InvocationTargetException

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#905]
### Modpack

Bagges Pack 1.7.10

### Game log

```java
[20:50:57] [Client thread/WARN] [PulseManager-TConstruct/TConstruct]: Caught exception in findAndInvokeHandlers: java.lang.reflect.InvocationTargetException
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at mantle.pulsar.control.PulseManager.findAndInvokeHandlers(PulseManager.java:237)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at mantle.pulsar.control.PulseManager.postInit(PulseManager.java:216)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at tconstruct.TConstruct.postInit(TConstruct.java:239)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:8993)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.ArrayList.get(ArrayList.java:435)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at tconstruct.plugins.gears.TinkerGears.postInit(TinkerGears.java:75)
[20:50:57] [Client thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 46 more
```

### Description

???

**Comment by quentin452** [comment]
Fixed in V0.94.83 by updating OptimizationsAndTweaks
