### ISSUE TITLE
[1.7.10]: RemoteIO : Unable to access any field [languageList, field_74816_c, d]

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#907]
### Modpack

Bagges Pack 1.7.10

### Game log

```java
[20:52:09] [Client thread/ERROR] [FML/]: Unable to access any field [languageList, field_74816_c, d] on type net.minecraft.util.StringTranslate
cpw.mods.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.NullPointerException
	at cpw.mods.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:121) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:60) [ObfuscationReflectionHelper.class:?]
	at remoteio.common.core.handler.LocalizationUpdater$StringTranslateDelegate.inject(LocalizationUpdater.java:148) [LocalizationUpdater$StringTranslateDelegate.class:?]
	at remoteio.common.core.handler.LocalizationUpdater.loadLangFiles(LocalizationUpdater.java:119) [LocalizationUpdater.class:?]
	at remoteio.common.core.handler.LocalizationUpdater.access$500(LocalizationUpdater.java:27) [LocalizationUpdater.class:?]
	at remoteio.common.core.handler.LocalizationUpdater$2.func_110549_a(LocalizationUpdater.java:106) [LocalizationUpdater$2.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:609) [bao.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:8993) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
```

### Description

?????

**Comment by quentin452** [comment]
Fixed in V0.94.83 by updating OptimizationsAndTweaks (disabling loalizationUpdater)
