### ISSUE TITLE
[1.7.10]: Bird Nests

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#910]
### Modpack

Bagges Pack 1.7.10 V0.94.81

### Game log

```java
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://raw.githubusercontent.com/cleverpanda/BirdsNests/master/update.json
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URL.openStream(URL.java:1038)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at panda.birdsnests.VersionChecker.run(VersionChecker.java:32)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.Reader.<init>(Reader.java:78)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:968)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at panda.birdsnests.VersionChecker.run(VersionChecker.java:48)
[14:34:16] [Nests Version Check/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)```

### Description

.

**Comment by quentin452** [comment]
Fixed in V0.94.83 by updating OptimizationsAndTweaks
