### ISSUE TITLE
[1.7.10]: anchormanMod

### ISSUE THREAD

**Issue by GamebP** [quentin452/1.7.10-Forge-renewed-v1#912]
### Modpack

Bagges Pack 1.7.10 V0.94.81

### Game log

```java
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/133619815/BriniumModders%20Cloud/registeredUsers.txt
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URL.openStream(URL.java:1038)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mc.Mitchellbrine.anchormanMod.util.CloudChecking.userValidation(CloudChecking.java:17)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mc.Mitchellbrine.anchormanMod.util.CloudChecking.isUserRegistered(CloudChecking.java:30)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mc.Mitchellbrine.anchormanMod.common.event.LivingMagicalMurderEvent.playerValidation(LivingMagicalMurderEvent.java:215)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_3725_LivingMagicalMurderEvent_playerValidation_EntityJoinWorldEvent.invoke(.dynamic)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72838_d(World.java:1334)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(ServerConfigurationManager.java:301)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:161)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2257)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:2572)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2329)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$$Lambda$1864/1029916813.run(Unknown Source)
[15:03:10] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: https://dl.dropboxusercontent.com/u/23446861/Mods/BuildHelper/check.txt
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URL.openStream(URL.java:1038)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.slymask3.buildhelper.handler.ConnectionHandler.onClientConnection(ConnectionHandler.java:26)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_728_ConnectionHandler_onClientConnection_PlayerLoggedInEvent.invoke(.dynamic)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:2257)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:2572)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:2329)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$$Lambda$1864/1029916813.run(Unknown Source)
[15:03:11] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
```

### Description

 .

**Comment by quentin452** [comment]
dupplicated #911
