### ISSUE TITLE
[1.7.10]: Spam log when teleporting to Land of Darkness , /cofh tpx -2374

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#936]
### Modpack

 Biggess Pack Cat Edition V0.98.8DEV

### Game log

```
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:1027)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:68)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:750)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:1027)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:68)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:750)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:1027)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:68)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:750)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.tileentity.TileEntity.func_145838_q(TileEntity.java:1027)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:68)
[20:22:53] [CullThread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:750)
```
### Description

spam log when teleporting to Land of Darkness , /cofh tpx -2374 (Fossil and archeology mod)

**Comment by quentin452** [comment]
It seem thats Fixed in Biggess Pack Cat Edition V0.98.8
