### ISSUE TITLE
[1.7.10]:  Achievement Detection Fix loaded a new chunk when going to dimension anotherWorld , /cofh tpx 212

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#938]
### Modpack

Biggess Pack Cat Edition V0.98.8DEV

### Game log

```
[23:02:53] [Server thread/WARN] [ArchaicFix/]: Achievement Detection Fix loaded a new chunk [-8, 1] in dimension 0 (Overworld) while populating chunk [-9, 1], causing cascading worldgen lag.
[23:02:53] [Server thread/WARN] [ArchaicFix/]: Please report this to the mod's issue tracker. This log can be disabled in the ArchaicFix config.
[23:02:53] [Server thread/WARN] [ArchaicFix/]: Stacktrace
java.lang.Exception: Cascading world generation
	at net.minecraft.world.chunk.Chunk.logCascadingWorldGeneration(Chunk.java:6655) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zob000$archaicfix$savePopulatingChunk(Chunk.java:6661) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java) ~[apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:2673) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:2647) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:2637) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_72938_d(World.java:414) ~[ahb.class:?]
	at net.minecraft.world.World.func_72825_h(World.java:1742) ~[ahb.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:124) ~[aia.class:?]
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:105) ~[aia.class:?]
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339) ~[ahu.class:?]
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesPop.populate(MysteriumPatchesFixesPop.java:220) ~[MysteriumPatchesFixesPop.class:?]
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java) ~[aqz.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:6503) ~[apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:2673) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:2647) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:2637) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.optimizationsAndTweaks$getChunkBlockLightValue(World.java:51900) ~[ahb.class:?]
	at net.minecraft.world.World.func_72849_a(World.java:51857) ~[ahb.class:?]
	at net.minecraft.world.World.func_72957_l(World.java:764) ~[ahb.class:?]
	at net.minecraft.block.BlockGrass.handler$zgf001$updateTick(BlockGrass.java:1028) ~[alh.class:?]
	at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java) ~[alh.class:?]
	at fr.iamacat.optimizationsandtweaks.utils.optimizationsandtweaks.vanilla.WorldServerTwo.optimizationsAndTweaks$handleBlockTick(WorldServerTwo.java:146) ~[WorldServerTwo.class:?]
	at fr.iamacat.optimizationsandtweaks.utils.optimizationsandtweaks.vanilla.WorldServerTwo.optimizationsAndTweaks$handleBlockTicks(WorldServerTwo.java:128) ~[WorldServerTwo.class:?]
	at fr.iamacat.optimizationsandtweaks.utils.optimizationsandtweaks.vanilla.WorldServerTwo.optimizationsAndTweaks$processChunk(WorldServerTwo.java:29) ~[WorldServerTwo.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:1261) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:1323) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:3230) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:3576) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:3333) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_432]
```

### Description

 Achievement Detection Fix loaded a new chunk when going to dimension anotherWorld , /cofh tpx 212 (Parallel World)

**Comment by quentin452** [comment]
Fixed in Biggess Pack Cat Edition V0.98.8
