### ISSUE TITLE
[1.7.10]: Torment Dimension from witchery not compatible with endlessids

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#940]
### Modpack

Biggess Pack Cat Edition V0.98.8DEV

### Game log

```
java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
	at net.minecraft.world.chunk.Chunk.eid$emergencyCrash(Chunk.java:1654)
	at net.minecraft.world.chunk.Chunk.handler$zbh000$endlessids$crashGetBiomeArray(Chunk.java:1668)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at com.emoniph.witchery.dimension.WorldChunkManagerTorment.func_73154_d(älDuaQhTsHRVlv5gRlkUUew==öYnKEzöü)
	at net.minecraft.world.gen.ChunkProviderServer.redirect$zjg000$angelica$sodium$populateChunkWithBiomes(ChunkProviderServer.java:515)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:2676)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:2647)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:2637)
	at fr.iamacat.optimizationsandtweaks.utils.optimizationsandtweaks.vanilla.WorldServerTwo.optimizationsAndTweaks$processChunk(WorldServerTwo.java:26)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:1261)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:1323)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:3230)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:3576)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:3333)
	at java.lang.Thread.run(Thread.java:750)
```

### Description

Torment Dimension from witchery not compatible with endlessids , /cofh tpx -38

**Comment by quentin452** [comment]
Fixed in Biggess Pack Cat Edition V0.98.8
