### ISSUE TITLE
[1.7.10]: Crash when teleporting to MiddleEarth , /cofh tpx 28100

### ISSUE THREAD

**Issue by quentin452** [quentin452/1.7.10-Forge-renewed-v1#941]
### Modpack

Biggess Pack Cat Edition V0.98.8DEV

### Game log

```
java.lang.NullPointerException: Unexpected error
	at lotr.client.LOTRTickHandlerClient.onRenderFog(LOTRTickHandlerClient.java:1190)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_LOTRTickHandlerClient_onRenderFog_RenderFogEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_78468_a(EntityRenderer.java:4137)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:3291)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:3118)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:9006)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

### Description

Crash when teleporting to MiddleEarth , /cofh tpx 28100 [Lotr mod]

**Comment by quentin452** [comment]
Fixed in Biggess Pack Cat Edition V0.98.8
